'use client';

import { useState } from 'react';
import { Beaker, BookOpen, BrainCircuit, Check, ChevronRight, Clock3, FlaskConical, Pause, Play, RotateCcw, Search, Sparkles, Zap } from 'lucide-react';
import { ReactionCanvas } from '@/components/ReactionCanvas';

const categories = ['All reactions', 'Acid-base', 'Redox', 'Organic', 'Biochemistry'];
const reactions = [{ name: 'Neutralization', formula: 'HCl + NaOH -> NaCl + H2O', type: 'Acid-base', time: '02:40', color: 'bg-[#d9f99d]' }, { name: 'Electrolysis of water', formula: '2H2O -> 2H2 + O2', type: 'Redox', time: '03:15', color: 'bg-[#bae6fd]' }, { name: 'Esterification', formula: 'Acid + Alcohol -> Ester', type: 'Organic', time: '04:20', color: 'bg-[#fde68a]' }];

function Panel({ title, icon: Icon, children, className = '' }: { title: string; icon: typeof Beaker; children: React.ReactNode; className?: string }) {
  return <section className={`rounded-2xl border border-[#e6eee6] bg-white p-5 ${className}`}><div className="mb-4 flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#eaf5eb] text-forest"><Icon size={16} /></span><h2 className="text-sm font-bold text-ink">{title}</h2></div>{children}</section>;
}

export function ReactionStudio() {
  const [category, setCategory] = useState('All reactions');
  const [selected, setSelected] = useState(reactions[0]);
  const [isPlaying, setIsPlaying] = useState(false);
  const [time, setTime] = useState('00:00');
  const filtered = category === 'All reactions' ? reactions : reactions.filter((reaction) => reaction.type === category);

  function reset() { setIsPlaying(false); setTime('00:00'); }

  return <main className="min-h-[calc(100vh-72px)] bg-[#f7faf6] px-4 py-7 sm:px-8 sm:py-10 lg:px-12"><div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.2em] text-leaf">Phase 4 / scientific workspace</p><h1 className="text-3xl font-bold tracking-[-.05em] text-ink md:text-4xl">Reaction Studio</h1><p className="mt-2 max-w-xl text-sm text-[#718079]">Explore how molecules transform, one guided step at a time.</p></div><div className="flex items-center gap-2 rounded-xl border border-[#e6eee6] bg-white px-3 py-2 text-xs font-semibold text-[#718079]"><span className="h-2 w-2 rounded-full bg-leaf" /> Preview mode</div></div>
      <div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)] xl:grid-cols-[220px_minmax(0,1fr)_260px]"><aside className="rounded-2xl border border-[#e6eee6] bg-white p-4"><div className="mb-4 flex items-center gap-2 px-1"><BookOpen size={16} className="text-forest" /><h2 className="text-sm font-bold text-ink">Reaction library</h2></div><label className="mb-4 flex items-center gap-2 rounded-lg border border-[#e6eee6] px-3 py-2 text-xs text-[#98a69d]"><Search size={14} /><input aria-label="Search reactions" placeholder="Search library" className="w-full bg-transparent outline-none placeholder:text-[#98a69d]" /></label><div className="mb-5 space-y-1">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-xs font-semibold ${category === item ? 'bg-[#eaf5eb] text-forest' : 'text-[#718079] hover:bg-mist'}`}>{item}{category === item && <Check size={14} />}</button>)}</div><div className="border-t border-[#e6eee6] pt-4"><p className="mb-3 px-1 text-[10px] font-bold uppercase tracking-[.16em] text-[#98a69d]">Featured</p>{filtered.map((reaction) => <button key={reaction.name} onClick={() => { setSelected(reaction); reset(); }} className={`mb-2 w-full rounded-xl border p-3 text-left transition ${selected.name === reaction.name ? 'border-forest/30 bg-[#f5faf3]' : 'border-transparent hover:border-[#e6eee6]'}`}><span className={`mb-2 block h-1.5 w-8 rounded-full ${reaction.color}`} /><span className="block text-xs font-bold text-ink">{reaction.name}</span><span className="mt-1 block text-[10px] text-[#98a69d]">{reaction.time} / {reaction.type}</span></button>)}</div></aside>
        <div className="space-y-6"><ReactionCanvas isPlaying={isPlaying} onReset={reset} /><Panel title="Chemical equation" icon={FlaskConical}><div className="flex flex-wrap items-center justify-center gap-3 rounded-xl bg-[#f5f8f3] px-4 py-5 text-center font-mono text-sm text-ink sm:text-base"><span>HCl</span><span className="text-leaf">+</span><span>NaOH</span><span className="text-[#98a69d]">-&gt;</span><span>NaCl</span><span className="text-leaf">+</span><span>H2O</span></div><div className="mt-5 flex items-center justify-center gap-2"><button onClick={() => { setIsPlaying((value) => !value); setTime(isPlaying ? '00:00' : '00:18'); }} className="flex items-center gap-2 rounded-lg bg-forest px-4 py-2 text-xs font-bold text-white">{isPlaying ? <Pause size={14} /> : <Play size={14} />}{isPlaying ? 'Pause' : 'Play'}</button><button onClick={reset} aria-label="Reset reaction" title="Reset reaction" className="grid h-8 w-8 place-items-center rounded-lg border border-[#e6eee6] text-[#718079] hover:text-forest"><RotateCcw size={14} /></button></div></Panel><Panel title="Reaction timeline" icon={Clock3}><div className="relative px-1 pb-1"><div className="absolute left-2 right-2 top-2 h-1 rounded-full bg-[#eaf5eb]" /><div className="relative flex justify-between"><span className="h-5 w-5 rounded-full border-4 border-[#b7f34a] bg-white" /><span className="h-5 w-5 rounded-full border-4 border-[#dcebdc] bg-white" /><span className="h-5 w-5 rounded-full border-4 border-[#dcebdc] bg-white" /><span className="h-5 w-5 rounded-full border-4 border-[#dcebdc] bg-white" /></div><div className="mt-3 flex justify-between text-[10px] text-[#98a69d]"><span>Reactants</span><span>Collision</span><span>Transfer</span><span>Products</span></div><p className="mt-4 text-center text-xs font-semibold text-forest">{time} / 02:40</p></div></Panel></div>
        <aside className="space-y-6 lg:col-span-2 xl:col-span-1"><Panel title="Reaction information" icon={Beaker}><dl className="space-y-3 text-xs"><div className="flex justify-between gap-3"><dt className="text-[#98a69d]">Selected reaction</dt><dd className="text-right font-semibold text-ink">{selected.name}</dd></div><div className="flex justify-between gap-3"><dt className="text-[#98a69d]">Category</dt><dd className="font-semibold text-ink">{selected.type}</dd></div><div className="flex justify-between gap-3"><dt className="text-[#98a69d]">Energy profile</dt><dd className="font-semibold text-forest">Exothermic</dd></div><div className="flex justify-between gap-3"><dt className="text-[#98a69d]">Progress</dt><dd className="font-semibold text-ink">{time}</dd></div></dl><div className="mt-5 flex items-center gap-2 rounded-lg bg-[#f5f8f3] p-3 text-[10px] leading-4 text-[#718079]"><Zap size={14} className="shrink-0 text-leaf" /> Guided 3D visualization ready</div></Panel><Panel title="AI explanation" icon={BrainCircuit} className="bg-[#14251b] text-white"><div className="flex items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#b7f34a] text-[#14251b]"><Sparkles size={15} /></span><p className="text-xs leading-5 text-white/70">An acid and a base exchange ions. The hydrogen and hydroxide ions combine to form water, while sodium and chloride remain as salt.</p></div><button className="mt-5 flex items-center gap-1 text-xs font-bold text-[#b7f34a]">Explore concept <ChevronRight size={14} /></button></Panel></aside></div></div></main>;
}